In [ ]:
pip install pandas

In [5]:
import numpy as np
import pandas as pd
import os

In [11]:
for dirname, _, filenames in os.walk('./data'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

./data/.DS_Store
./data/music.csv
./data/animethemes.json
./data/movie_fields.json
./data/music_fields.json
./data/animethemes_fields.json
./data/movie.csv

In [ ]:
music_field = pd.read_json("./data/music_fields.json")
music_field.head()

,file,description,fields
0,music.csv,外部團隊參考用的音樂資料欄位說明。,"{'name': 'song_id', 'type': 'string', 'descrip..."
1,music.csv,外部團隊參考用的音樂資料欄位說明。,"{'name': 'artist_id', 'type': 'string', 'descr..."
2,music.csv,外部團隊參考用的音樂資料欄位說明。,"{'name': 'title', 'type': 'string', 'descripti..."
3,music.csv,外部團隊參考用的音樂資料欄位說明。,"{'name': 'artist', 'type': 'string', 'descript..."
4,music.csv,外部團隊參考用的音樂資料欄位說明。,"{'name': 'isrc', 'type': 'string', 'descriptio..."

In [33]:
music_field.info()

<class 'pandas.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   file         14 non-null     str
 1   description  14 non-null     str
 2   fields       14 non-null     object
dtypes: object(1), str(2)
memory usage: 468.0+ bytes

In [25]:
music = pd.read_csv("./data/music.csv")

ParserError: Error tokenizing data. C error: Expected 14 fields in line 268, saw 16

In [ ]:
with open("./data/music.csv", "r", encoding="utf-8") as f:
    for i, line in enumerate(f):
        if i == 267:  # 程式從 0 開始數，第 268 列就是 index 267
            print(line)
            break

song_267,artist_2,BRAVE,嵐,JPQ401900750,2019,jpn,日語歌曲,日語歌曲|世界音樂,Travel & Music|World / Spiritual|Various|J-POP(JP)|Independent(JP),BRAVE,"Fredrik \"Figge\" Bostrom, Goro.T, 櫻井翔","",""

In [26]:
music = pd.read_csv("./data/music.csv", escapechar='\\')
music.head()

,song_id,artist_id,title,artist,isrc,release_year,locale,song_language,genres,song_category,album_name,song_composer,song_lyricist,song_producer
0,song_1,artist_1,IRIS OUT,米津玄師,JPU902502821,2025,jpn,日語歌曲,日語歌曲|流行樂,Various|J-POP(JP)|J-POP(JP)|Independent(JP),IRIS OUT,Kenshi Yonezu,Kenshi Yonezu,Kenshi Yonezu
1,song_2,artist_2,Five,嵐,JPQ402600330,2026,jpn,日語歌曲,日語歌曲|世界音樂,Travel & Music|World / Spiritual|Various|J-POP...,Five,"HIKARI, Tomoki Ishizuka",HIKARI,NaN
2,song_3,artist_3,AIZO,King Gnu,JPU902504639,2026,jpn,日語歌曲,日語歌曲|另類,Alternative Rock(new_JP)|Various|Alternative /...,AIZO,DAIKI TSUNETA,DAIKI TSUNETA,NaN
3,song_4,artist_4,Again,Mr.Children,JPTF02538202,2026,jpn,日語歌曲,日語歌曲|流行樂,J-POP(JP)|Various|J-POP(JP)|Independent(JP),Again,Kazutoshi Sakurai,Kazutoshi Sakurai,NaN
4,song_5,artist_5,革命道中 - On The Way,アイナ・ジ・エンド,JPB602501972,2025,jpn,日語歌曲,日語歌曲|流行樂,Independent(JP)|J-POP(JP)|Various|J-POP(JP),革命道中 - On The Way,アイナ・ジ・エンド/Shin Sakiura,アイナ・ジ・エンド/Shin Sakiura,NaN

In [27]:
music.info()

<class 'pandas.DataFrame'>
RangeIndex: 1986 entries, 0 to 1985
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   song_id        1986 non-null   str
 1   artist_id      1986 non-null   str
 2   title          1986 non-null   str
 3   artist         1986 non-null   str
 4   isrc           1986 non-null   str
 5   release_year   1986 non-null   int64
 6   locale         1955 non-null   str
 7   song_language  1955 non-null   str
 8   genres         1966 non-null   str
 9   song_category  1955 non-null   str
 10  album_name     1986 non-null   str
 11  song_composer  1571 non-null   str
 12  song_lyricist  1366 non-null   str
 13  song_producer  620 non-null    str
dtypes: int64(1), str(13)
memory usage: 217.3 KB

In [ ]:
music[music['song_producer'].isnull()]
#詢問業主song_producer是否重要

,song_id,artist_id,title,artist,isrc,release_year,locale,song_language,genres,song_category,album_name,song_composer,song_lyricist,song_producer
1,song_2,artist_2,Five,嵐,JPQ402600330,2026,jpn,日語歌曲,日語歌曲|世界音樂,Travel & Music|World / Spiritual|Various|J-POP...,Five,"HIKARI, Tomoki Ishizuka",HIKARI,NaN
2,song_3,artist_3,AIZO,King Gnu,JPU902504639,2026,jpn,日語歌曲,日語歌曲|另類,Alternative Rock(new_JP)|Various|Alternative /...,AIZO,DAIKI TSUNETA,DAIKI TSUNETA,NaN
3,song_4,artist_4,Again,Mr.Children,JPTF02538202,2026,jpn,日語歌曲,日語歌曲|流行樂,J-POP(JP)|Various|J-POP(JP)|Independent(JP),Again,Kazutoshi Sakurai,Kazutoshi Sakurai,NaN
4,song_5,artist_5,革命道中 - On The Way,アイナ・ジ・エンド,JPB602501972,2025,jpn,日語歌曲,日語歌曲|流行樂,Independent(JP)|J-POP(JP)|Various|J-POP(JP),革命道中 - On The Way,アイナ・ジ・エンド/Shin Sakiura,アイナ・ジ・エンド/Shin Sakiura,NaN
5,song_6,artist_6,好きすぎて滅！,M!LK,JPVI02502804,2025,jpn,日語歌曲,日語歌曲|流行樂,J-POP(JP)|Independent(JP)|J-POP(JP)|Various,好きすぎて滅！,浅野尚志,MUTEKI DEAD SNAKE,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1981,song_1982,artist_278,今宵の月のように,エレファントカシマシ,JPPC09715029,1997,jpn,日語歌曲,日語歌曲|搖滾,Various|J-POP(JP)|Independent(JP)|J-ROCK(JP),明日に向かって走れ-月夜の歌-,NaN,NaN,NaN
1982,song_1983,artist_15,Doctor,ちゃんみな,JPWP01801227,2018,jpn,日語歌曲,日語歌曲|嘻哈饒舌,Hip-Hop / Rap|J-POP(JP)|Independent(JP),Doctor,"chanmina, JIGG",chanmina,NaN
1983,song_1984,artist_17,破顔,Official髭男dism,JPPC02211341,2022,jpn,日語歌曲,日語歌曲|流行樂,Various|J-POP(JP)|J-POP(JP)|Independent(JP),ミックスナッツEP,藤原聡,藤原聡,NaN
1984,song_1985,artist_75,ピクルス,こっちのけんと,JPU902503089,2025,jpn,日語歌曲,日語歌曲|流行樂,J-POP(JP)|Various|Independent(JP)|J-POP(JP),ピクルス,"Kocchi no Kento, GRP",Kocchi no Kento,NaN
1985,song_1986,artist_52,雨のち晴レルヤ,ゆず,JPTF01314101,2013,jpn,日語歌曲,日語歌曲,J-POP(JP)|Various|Independent(JP)|J-POP(JP),雨のち晴レルヤ/守ってあげたい,NaN,NaN,NaN

In [ ]:
music.describe()
#檢測數值資料是否合理，年份是否為範圍內資料

       release_year
count   1986.000000
mean    2016.380665
std       10.645992
min     1970.000000
25%     2011.000000
50%     2020.000000
75%     2025.000000
max     2026.000000

In [ ]:
music.duplicated().sum()
#如果有，則drop_duplicates

np.int64(0)